# Generated by Django 5.2 on 2025-05-11 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=10)),
                ('DiscountValue', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('Comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('ingredients', models.CharField(max_length=500)),
                ('brandName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.colors')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inStock', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.categories')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.products')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalRevenue', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('totalSoldItems', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.products')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=200)),
                ('PromoCodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.promocode')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TotalPrice', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('TotalItems', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.products')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.products')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
    ]
